name: biocheck_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  battery_plus: ^2.0.1
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  get: 4.3.8
  get_storage: ^2.0.3
  local_auth: ^1.1.8
  location: ^4.2.0
  reactive_forms: ^10.6.2
  sqflite: ^2.0.0+4
  path_provider: ^2.0.6
  cached_network_image: ^3.1.0+1
  cloud_firestore: ^3.1.0
<<<<<<< HEAD
  firebase_auth: ^3.3.0
=======
>>>>>>> main

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Airbnb
      fonts:
        - asset: assets/fonts/AirbnbCerealLight.ttf
          weight: 300
        - asset: assets/fonts/AirbnbCerealMedium.ttf
          weight: 400
        - asset: assets/fonts/AirbnbCerealBold.ttf
          weight: 700
        - asset: assets/fonts/AirbnbCerealExtraBold.ttf
          weight: 900
  assets:
    - assets/
